#!/bin/bash

function list_branches
{
  if [ -n "$1" ] && [ "$1" = "-a" ]; then
    git branch -a
    exit 0
  elif [ -z "$1" ]; then
    git branch
    exit 0
  fi
}

list_branches "$1"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
NAME="$1"

case $key in
    -f|--feature)
    FEATURE="YES"
    NAME="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--pull)
    REFRESH="YES"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$NAME" ]
then
  echo "Must provide branch name"
  exit 0
fi

if [ -z "$FEATURE" ]; then
  BRANCH_NAME="$NAME"
else
  BRANCH_NAME="feature/LAM-${NAME}"
fi

EXISTS=`git branch --list $BRANCH_NAME`
if [ -n "$EXISTS" ]
then
  git checkout "$BRANCH_NAME"
  exit 1
fi

echo "Create ${BRANCH_NAME} ? y/n"
read IN

if [ -z "$IN" ] || [ "$IN" == "n" ] || [ "$IN" == "N" ]
then
  exit 0
fi

if [ -n "$REFRESH" ]
then
  git pull && git checkout -b "$BRANCH_NAME"
  exit 0;
fi

git checkout -b "$BRANCH_NAME"
