#!/bin/bash

sudo mkdir ~/.executes
sudo mkdir ~/.executes/bin

cp gp ~/.executes/bin
cp gf ~/.executes/bin
cp branch/branch ~/.executes/bin
cp branch/configure ~/.executes/bin

sudo chmod 754 ~/.executes/bin/gp
sudo chmod 754 ~/.executes/bin/gf
sudo chmod 754 ~/.executes/bin/branch
sudo chmod 754 ~/.executes/bin/configure
