#!/bin/bash

NAME="$1"
ACTIVITY="$2"

if [ -z "$NAME" ]; then
    echo "No app name provided (eg. com.company.app_name) or provide option."
    exit 0
fi

case "$NAME" in
    -d)
        echo "Opening developer menu..."
        adb shell input keyevent KEYCODE_MENU
        exit 1
    ;;
esac


if [ -z "$ACTIVITY" ]; then
    ACTIVITY="MainActivity"
fi

echo "Refreshing..."
adb shell am force-stop $NAME && adb shell am start -n $NAME/$NAME.$ACTIVITY

